bigmine2014_debatty.pdf: bigmine2014_debatty.tex bigmine2014_debatty.bib
	pdflatex bigmine2014_debatty.tex
	bibtex bigmine2014_debatty.aux
	pdflatex bigmine2014_debatty.tex
	pdflatex bigmine2014_debatty.tex


clean:
	rm *.aux *.bbl *.blg *.log *.out
